version: "3"

services:
  # Graylog stack
  app:
    depends_on: 
      - "fluent-bit"
    image: thakkaryash94/express-example:latest
    container_name: express-app
    ports:
      - "4000:3000"
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224


  loki:
    image: grafana/loki:latest
    container_name: loki
    expose:
      - "3100"


  grafana:
    image: grafana/grafana:7.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "grafana-storage:/var/lib/grafana"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug



  renderer:
    image: grafana/grafana-image-renderer:2.0.0
    container_name: grafana-image-renderer
    expose:
      - "8081"
    environment:
      ENABLE_METRICS: "true"


  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:latest
    container_name: fluent-bit
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"


      
# Graylog stack
  mongodb:
    image: mongo:3
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.security.audit.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  graylog:
    image: graylog/graylog:2.5
    container_name: graylog
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
      # - /var/log:/acessoexterno
    environment:
      # USER: admin
      # PASS: somepasswordpepper
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://0.0.0.0:9000/api
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - "9000:9000"       # Graylog web interface and REST API
      - "514:514"         # Syslog TCP
      - "514:514/udp"     # Syslog UDP
      - "12201:12201"     # GELF TCP
      - "12201:12201/udp" # GELF UDP
      - "5044:5044"


volumes:
  grafana-storage:

  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local
