version: "3"

services:
  app:
    depends_on: 
      - "fluent-bit"
    image: thakkaryash94/express-example:latest
    container_name: express-app
    ports:
      - "4000:3000"
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224


  loki:
    image: grafana/loki:latest
    container_name: loki
    expose:
      - "3100"


  grafana:
    image: grafana/grafana:7.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "grafana-storage:/var/lib/grafana"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug



  renderer:
    image: grafana/grafana-image-renderer:2.0.0
    container_name: grafana-image-renderer
    expose:
      - "8081"
    environment:
      ENABLE_METRICS: "true"


  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:latest
    container_name: fluent-bit
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"


volumes:
  grafana-storage:
    